import type { Metadata } from "next";
import { Roboto, PT_Serif, Roboto_Mono, Shantell_Sans } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";

const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ['cyrillic', 'latin'], variable: '--font-roboto' });
const robotoMono = Roboto_Mono({ weight: ['400', '500', '700'], subsets: ['cyrillic', 'latin'], variable: '--font-roboto-mono' });
const ptSerif = PT_Serif({ weight: ['400', '700'], subsets: ['cyrillic', 'latin'], variable: '--font-pt-serif' });
const shantellSans = Shantell_Sans({ weight: ['400', '500', '700'], subsets: ['cyrillic', 'latin'], variable: '--font-shantell-sans' });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const fontsClass = `${roboto.className} ${shantellSans.className} ${ptSerif.className} ${robotoMono.className}`;
  return (
    <html lang="en" className={`${fontsClass}`}>
      <head>
        <ThemeModeScript />
      </head>
      <body className={`${roboto.className} w-full dark:bg-dark-primary dark:text-white`}>
        {children}
      </body>
    </html>
  );
}
